spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/movielande
  username: postgres
  password: password

spring.flyway:
  user: postgres
  password: password
  schemas: public
  enabled: true
  locations: classpath:db/migration

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE