spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:2023/postgres
  username: postgres
  password: 1111

spring.flyway:
  user: postgres
  password: 1111
  schemas: public
  enabled: false
  locations: classpath:db/migration

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter: DEBUG
    org.springframework.security.web.access: DEBUG